// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"example.com/playground-wire-app/internal/app"
	"example.com/playground-wire-app/internal/config"
	"example.com/playground-wire-app/internal/dbconn"
	"example.com/playground-wire-app/internal/repo"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeApp() app.App {
	configConfig := config.ProvideConfig()
	conn := dbconn.ProvideDbConn(configConfig)
	repoRepo := repo.ProvideRepo(conn)
	appApp := app.ProvideApp(configConfig, repoRepo)
	return appApp
}

// wire.go:

var PersistenceSet = wire.NewSet(dbconn.ProvideDbConn, repo.ProvideRepo)
